# -*- coding: utf-8 -*-
"""test_import_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HX7BcL2dulqQyAssJqgTH15cGLyageVs
"""

import subprocess

def test_model_loading():
    try:
        # This will try to load the model and run the accuracy code from the import script
        subprocess.run(['python', 'import_script.py'], check=True)
        print("Model loaded and accuracy evaluated successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error during model loading or accuracy evaluation: {e}")
        raise

if __name__ == "__main__":
    test_model_loading()